default_platform(:ios)

APP_ID = "com.codybontecou.imghost"
KEY_ID = "T7KGDK4Y4V"
ISSUER_ID = "6c3b3640-c6bf-40a9-b6e5-57cda2c7776e"
KEY_PATH = "/Users/codybontecou/dev/AuthKey_T7KGDK4Y4V.p8"

platform :ios do
  desc "Submit for review"
  lane :submit do
    k = app_store_connect_api_key(
      key_id: KEY_ID,
      issuer_id: ISSUER_ID,
      key_filepath: KEY_PATH,
      in_house: false
    )
    deliver(
      api_key: k,
      app_identifier: APP_ID,
      app_version: "1.3",
      skip_binary_upload: true,
      skip_screenshots: true,
      run_precheck_before_submit: false,
      submit_for_review: true,
      automatic_release: true,
      force: true,
      platform: "ios",
      submission_information: {
        add_id_info_uses_idfa: false,
        export_compliance_uses_encryption: false
      }
    )
  end

  desc "Upload metadata"
  lane :upload_metadata do
    k = app_store_connect_api_key(
      key_id: KEY_ID,
      issuer_id: ISSUER_ID,
      key_filepath: KEY_PATH,
      in_house: false
    )
    deliver(
      api_key: k,
      app_identifier: APP_ID,
      app_version: "1.3",
      skip_binary_upload: true,
      skip_screenshots: true,
      run_precheck_before_submit: false,
      force: true,
      platform: "ios"
    )
  end
end

platform :mac do
  desc "Submit for review"
  lane :submit do
    k = app_store_connect_api_key(
      key_id: KEY_ID,
      issuer_id: ISSUER_ID,
      key_filepath: KEY_PATH,
      in_house: false
    )
    deliver(
      api_key: k,
      app_identifier: APP_ID,
      app_version: "1.3",
      skip_binary_upload: true,
      skip_screenshots: true,
      run_precheck_before_submit: false,
      submit_for_review: true,
      automatic_release: true,
      force: true,
      platform: "osx",
      submission_information: {
        add_id_info_uses_idfa: false,
        export_compliance_uses_encryption: false
      }
    )
  end

  desc "Upload metadata"
  lane :upload_metadata do
    k = app_store_connect_api_key(
      key_id: KEY_ID,
      issuer_id: ISSUER_ID,
      key_filepath: KEY_PATH,
      in_house: false
    )
    deliver(
      api_key: k,
      app_identifier: APP_ID,
      app_version: "1.3",
      skip_binary_upload: true,
      skip_screenshots: true,
      run_precheck_before_submit: false,
      force: true,
      platform: "osx"
    )
  end
end
